import "./globals.css";
import styles from "./layout.module.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className={styles.app}>
					<div className={styles.navbar}>Bookstore</div>

					<div className={styles.tabs}>
						<a href="/">
							<button className={styles.tab}>Home</button>
						</a>
						<a href="/newBook">
							<button className={styles.tab}>Add a book</button>
						</a>
						<a href="/search">
							<button className={styles.tab}>Search for books</button>
						</a>
					</div>

					{children}
				</div>
			</body>
		</html>
	);
}
